apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-wzjg
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0031-tenant/tkrw-pr712-0075-0031-app/devfile-sample-wzjg@sha256:19771d8f2e8f0d69ba2360e4aaa449342b63de0ac81a775d8c060735c4abbb20
        name: my-nodejs
        resources: {}
status: {}
